# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rspec'
gem 'rubocop-performance', require: false
gem 'rubocop-rspec', require: false
gem 'runger_release_assistant', require: false
gem 'runger_style', require: false
