name: Ruby

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runger_rails_model_explorer
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          bundler-cache: true
          working-directory: runger_rails_model_explorer

      - name: Run RuboCop
        run: bin/rubocop

      - name: Run RSpec
        run: bin/rspec
